project_name: "decoder-only-shakespeare"
seed: 42

comet:
  api_key: "sqAgtJu3JqBTsHLGMTekvp9GH"

data:
  train_text: "TinyShakespeare/train.csv"
  val_text: "TinyShakespeare/validation.csv"
  test_text: "TinyShakespeare/test.csv"

structural:
  d_model: 384
  n_layers: 6
  n_heads: 6
  d_ff: 1536
  seq_len: 256
  dropout: 0.1
  weight_decay: 0.01

training:
  batch_size: 32
  lr: 6e-4
  optimizer: "AdamW"
  warmup_steps: 100
  max_steps: 5000
  eval_interval: 200
  sample_interval: 500
  ckpt_interval: 1000
  epochs: 30

configurations:
  act_func: "ReLU"
  LN: "Post LN"
